b64_encode_up_a – BeFoR64
b64_encode_up_a Subroutine
20 statements
Source File
private pure subroutine b64_encode_up_a(up, code)
Encode an unlimited polymorphic array to base64.
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: up(1:)
Unlimited polymorphic variable to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
Calls
Called By
Source Code
b64_encode_up_a
Source Code
  pure subroutine b64_encode_up_a(up, code)
  !< Encode an unlimited polymorphic array to base64.
  class(*),                      intent(in)  :: up(1:) !< Unlimited polymorphic variable to be encoded.
  character(len=:), allocatable, intent(out) :: code   !< Encoded array.
  select type(up)
  type is(real(R8P))
    call b64_encode_R8_a(n=up,code=code)
  type is(real(R4P))
    call b64_encode_R4_a(n=up,code=code)
  type is(integer(I8P))
    call b64_encode_I8_a(n=up,code=code)
  type is(integer(I4P))
    call b64_encode_I4_a(n=up,code=code)
  type is(integer(I2P))
    call b64_encode_I2_a(n=up,code=code)
  type is(integer(I1P))
    call b64_encode_I1_a(n=up,code=code)
  type is(character(*))
    call b64_encode_string_a(s=up,code=code)
  endselect
  endsubroutine b64_encode_up_a
All Procedures
autotest b64_decode b64_decode_I1 b64_decode_I1_a b64_decode_I2 b64_decode_I2_a b64_decode_I4 b64_decode_I4_a b64_decode_I8 b64_decode_I8_a b64_decode_R16 b64_decode_R16_a b64_decode_R4 b64_decode_R4_a b64_decode_R8 b64_decode_R8_a b64_decode_string b64_decode_string_a b64_decode_up b64_decode_up b64_decode_up_a b64_encode b64_encode_I1 b64_encode_I1_a b64_encode_I2 b64_encode_I2_a b64_encode_I4 b64_encode_I4_a b64_encode_I8 b64_encode_I8_a b64_encode_R16 b64_encode_R16_a b64_encode_R4 b64_encode_R4_a b64_encode_R8 b64_encode_R8_a b64_encode_string b64_encode_string_a b64_encode_up b64_encode_up b64_encode_up_a b64_init decode_bits encode_bits pack_data pack_data_I1_I2 pack_data_I1_I4 pack_data_I1_I8 pack_data_I1_R4 pack_data_I1_R8 pack_data_I2_I1 pack_data_I2_I4 pack_data_I2_I8 pack_data_I2_R4 pack_data_I2_R8 pack_data_I4_I1 pack_data_I4_I2 pack_data_I4_I8 pack_data_I4_R4 pack_data_I4_R8 pack_data_I8_I1 pack_data_I8_I2 pack_data_I8_I4 pack_data_I8_R4 pack_data_I8_R8 pack_data_R4_I1 pack_data_R4_I2 pack_data_R4_I4 pack_data_R4_I8 pack_data_R4_R8 pack_data_R8_I1 pack_data_R8_I2 pack_data_R8_I4 pack_data_R8_I8 pack_data_R8_R4
Call graph
b64_encode_up_a calls b64_encode_i1_a, b64_encode_r8_a, b64_encode_i8_a, b64_encode_i2_a, b64_encode_r4_a, b64_encode_string_a, b64_encode_i4_a
b64_encode_i1_a calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_string_a calls encode_bits, byte_size
b64_encode_i4_a calls encode_bits
b64_encode_up calls b64_encode_up_a, b64_encode_up