b64_encode_R8_a – BeFoR64
b64_encode_R8_a Subroutine
15 statements
Source File
private pure subroutine b64_encode_R8_a(n, code)
Encode array numbers to base64 (R8P).
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(1:)
Array of numbers to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
Calls
Called By
Source Code
b64_encode_R8_a
Source Code
  pure subroutine b64_encode_R8_a(n, code)
  !< Encode array numbers to base64 (R8P).
  real(R8P),                     intent(in)  :: n(1:)   !< Array of numbers to be encoded.
  character(len=:), allocatable, intent(out) :: code    !< Encoded array.
  integer(I1P),     allocatable              :: nI1P(:) !< One byte integer array containing n.
  integer(I4P)                               :: padd    !< Number of padding characters ('=').
  integer(I8P)                               :: ns      !< Size of n.
  ns = size(n,dim=1)
  allocate(nI1P(1:((ns*BYR8P+2)/3)*3)) ; nI1P = 0_I1P
  code = repeat(' ',((ns*BYR8P+2)/3)*4)
  nI1P = transfer(n,nI1P)
  padd = mod((ns*BYR8P),3_I8P) ; if (padd>0_I4P) padd = 3_I4P - padd
  call encode_bits(bits=nI1P,padd=padd,code=code)
  endsubroutine b64_encode_R8_a
All Procedures
autotest b64_decode b64_decode_I1 b64_decode_I1_a b64_decode_I2 b64_decode_I2_a b64_decode_I4 b64_decode_I4_a b64_decode_I8 b64_decode_I8_a b64_decode_R16 b64_decode_R16_a b64_decode_R4 b64_decode_R4_a b64_decode_R8 b64_decode_R8_a b64_decode_string b64_decode_string_a b64_decode_up b64_decode_up b64_decode_up_a b64_encode b64_encode_I1 b64_encode_I1_a b64_encode_I2 b64_encode_I2_a b64_encode_I4 b64_encode_I4_a b64_encode_I8 b64_encode_I8_a b64_encode_R16 b64_encode_R16_a b64_encode_R4 b64_encode_R4_a b64_encode_R8 b64_encode_R8_a b64_encode_string b64_encode_string_a b64_encode_up b64_encode_up b64_encode_up_a b64_init decode_bits encode_bits pack_data pack_data_I1_I2 pack_data_I1_I4 pack_data_I1_I8 pack_data_I1_R4 pack_data_I1_R8 pack_data_I2_I1 pack_data_I2_I4 pack_data_I2_I8 pack_data_I2_R4 pack_data_I2_R8 pack_data_I4_I1 pack_data_I4_I2 pack_data_I4_I8 pack_data_I4_R4 pack_data_I4_R8 pack_data_I8_I1 pack_data_I8_I2 pack_data_I8_I4 pack_data_I8_R4 pack_data_I8_R8 pack_data_R4_I1 pack_data_R4_I2 pack_data_R4_I4 pack_data_R4_I8 pack_data_R4_R8 pack_data_R8_I1 pack_data_R8_I2 pack_data_R8_I4 pack_data_R8_I8 pack_data_R8_R4
Call graph
b64_encode_r8_a calls encode_bits
b64_encode_up_a calls b64_encode_r8_a
b64_encode_up calls b64_encode_up_a, b64_encode_up
b64_encode calls b64_encode_r8_a
autotest calls b64_encode
befor64_test calls autotest