encode_bits – BeFoR64
encode_bits Subroutine
31 statements
Source File
private pure subroutine encode_bits(bits, padd, code)
Encode a bits stream (must be multiple of 24 bits) into base64 charcaters code (of length multiple of 4).
The bits stream are encoded in chunks of 24 bits as the following example (in little endian order)
 +--first octet--+-second octet--+--third octet--+
 |7 6 5 4 3 2 1 0|7 6 5 4 3 2 1 0|7 6 5 4 3 2 1 0|
 +-----------+---+-------+-------+---+-----------+
 |5 4 3 2 1 0|5 4 3 2 1 0|5 4 3 2 1 0|5 4 3 2 1 0|
 +--1.index--+--2.index--+--3.index--+--4.index--+
Note
The 4 indexes are stored into 4 elements 8 bits array, thus 2 bits of each array element are not used.
Note
The number of paddings must be computed outside this procedure, into the calling scope.
Warning
This procedure is the backend of encoding, thus it must be never called outside the module.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: bits(1:)
Bits to be encoded.
integer(kind=I4P), intent(in) :: padd
Number of padding characters ('=').
character(len=*), intent(out) :: code
Characters code.
Called By
Source Code
encode_bits
Source Code
   pure subroutine encode_bits(bits, padd, code)
   !< Encode a bits stream (must be multiple of 24 bits) into base64 charcaters code (of length multiple of 4).
   !<
   !< The bits stream are encoded in chunks of 24 bits as the following example (in little endian order)
   !<```
   !< +--first octet--+-second octet--+--third octet--+
   !< |7 6 5 4 3 2 1 0|7 6 5 4 3 2 1 0|7 6 5 4 3 2 1 0|
   !< +-----------+---+-------+-------+---+-----------+
   !< |5 4 3 2 1 0|5 4 3 2 1 0|5 4 3 2 1 0|5 4 3 2 1 0|
   !< +--1.index--+--2.index--+--3.index--+--4.index--+
   !<```
   !< @note The 4 indexes are stored into 4 elements 8 bits array, thus 2 bits of each array element are not used.
   !<
   !< @note The number of paddings must be computed outside this procedure, into the calling scope.
   !<
   !< @warning This procedure is the backend of encoding, thus it must be never called outside the module.
   integer(I1P), intent(in)  :: bits(1:)  !< Bits to be encoded.
   integer(I4P), intent(in)  :: padd      !< Number of padding characters ('=').
   character(*), intent(out) :: code      !< Characters code.
   integer(I1P)              :: sixb(1:4) !< 6 bits slices (stored into 8 bits integer) of 24 bits input.
   integer(I8P)              :: c         !< Counter.
   integer(I8P)              :: e         !< Counter.
   integer(I8P)              :: Nb        !< Length of bits array.
   Nb=size(bits,dim=1,kind=I8P)
   c = 1_I8P
   do e=1_I8P,Nb,3_I8P ! loop over array elements: 3 bytes (24 bits) scanning
      sixb = 0_I1P
         call mvbits(bits(e  ),2,6,sixb(1),0)
         call mvbits(bits(e  ),0,2,sixb(2),4)
      if (e+1<=Nb) then
         call mvbits(bits(e+1),4,4,sixb(2),0)
         call mvbits(bits(e+1),0,4,sixb(3),2)
      endif
      if (e+2<=Nb) then
         call mvbits(bits(e+2),6,2,sixb(3),0)
         call mvbits(bits(e+2),0,6,sixb(4),0)
      endif
      sixb = sixb + 1_I1P
      code(c  :c  ) = base64(sixb(1):sixb(1))
      code(c+1:c+1) = base64(sixb(2):sixb(2))
      code(c+2:c+2) = base64(sixb(3):sixb(3))
      code(c+3:c+3) = base64(sixb(4):sixb(4))
      c = c + 4_I8P
   enddo
   if (padd>0) code(len(code)-padd+1:)=repeat('=',padd)
   endsubroutine encode_bits
All Procedures
b64_decode b64_decode_I1 b64_decode_I1_a b64_decode_I2 b64_decode_I2_a b64_decode_I4 b64_decode_I4_a b64_decode_I8 b64_decode_I8_a b64_decode_R16 b64_decode_R16_a b64_decode_R4 b64_decode_R4_a b64_decode_R8 b64_decode_R8_a b64_decode_string b64_decode_string_a b64_decode_up b64_decode_up b64_decode_up_a b64_encode b64_encode_I1 b64_encode_I1_a b64_encode_I2 b64_encode_I2_a b64_encode_I4 b64_encode_I4_a b64_encode_I8 b64_encode_I8_a b64_encode_R16 b64_encode_R16_a b64_encode_R4 b64_encode_R4_a b64_encode_R8 b64_encode_R8_a b64_encode_string b64_encode_string_a b64_encode_up b64_encode_up b64_encode_up_a b64_init decode_bits encode_bits pack_data pack_data_I1_I2 pack_data_I1_I4 pack_data_I1_I8 pack_data_I1_R4 pack_data_I1_R8 pack_data_I2_I1 pack_data_I2_I4 pack_data_I2_I8 pack_data_I2_R4 pack_data_I2_R8 pack_data_I4_I1 pack_data_I4_I2 pack_data_I4_I8 pack_data_I4_R4 pack_data_I4_R8 pack_data_I8_I1 pack_data_I8_I2 pack_data_I8_I4 pack_data_I8_R4 pack_data_I8_R8 pack_data_R4_I1 pack_data_R4_I2 pack_data_R4_I4 pack_data_R4_I8 pack_data_R4_R8 pack_data_R8_I1 pack_data_R8_I2 pack_data_R8_I4 pack_data_R8_I8 pack_data_R8_R4
Call graph
b64_encode_r16 calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_i1 calls encode_bits
b64_encode_string_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_string calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_r16_a calls encode_bits
b64_encode_up calls b64_encode_r4, b64_encode_i1, b64_encode_i2, b64_encode_string, b64_encode_i8, b64_encode_r8, b64_encode_i4, b64_encode_up_a, b64_encode_up
b64_encode calls b64_encode_r4, b64_encode_r4_a, b64_encode_i8_a, b64_encode_i1, b64_encode_string_a, b64_encode_i2, b64_encode_string, b64_encode_i1_a, b64_encode_r8_a, b64_encode_i8, b64_encode_i2_a, b64_encode_i4_a, b64_encode_r8, b64_encode_i4
volatile_doctest calls b64_encode
b64_encode_up_a calls b64_encode_r4_a, b64_encode_i8_a, b64_encode_string_a, b64_encode_i1_a, b64_encode_r8_a, b64_encode_i2_a, b64_encode_i4_a