pack_data_I2_R4 – BeFoR64
pack_data_I2_R4 Subroutine
10 statements
Source File
private pure subroutine pack_data_I2_R4(a1, a2, packed)
Pack different kinds of data into single I1P array.
 use befor64
 use penf
 integer(I2P)              :: a1(1)
 real(R4P)                 :: a2(1)
 integer(I1P), allocatable :: pack(:)
 a1(1) = 0
 a2(1) = 1
 call pack_data(a1=a1, a2=a2, packed=pack)
 print *, pack(size(pack, dim=1))
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
First data stream.
real(kind=R4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
Called By
Source Code
pack_data_I2_R4
Source Code
   pure subroutine pack_data_I2_R4(a1, a2, packed)
   !< Pack different kinds of data into single I1P array.
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< integer(I2P)              :: a1(1)
   !< real(R4P)                 :: a2(1)
   !< integer(I1P), allocatable :: pack(:)
   !< a1(1) = 0
   !< a2(1) = 1
   !< call pack_data(a1=a1, a2=a2, packed=pack)
   !< print *, pack(size(pack, dim=1))
   !<```
   !=> 63 <<<
   integer(I2P),              intent(in)    :: a1(1:)    !< First data stream.
   real(R4P),                 intent(in)    :: a2(1:)    !< Second data stream.
   integer(I1P), allocatable, intent(inout) :: packed(:) !< Packed data into I1P array.
   integer(I1P), allocatable                :: p1(:)     !< Temporary packed data of first stream.
   integer(I1P), allocatable                :: p2(:)     !< Temporary packed data of second stream.
   p1 = transfer(a1,p1)
   p2 = transfer(a2,p2)
   packed = [p1,p2]
   endsubroutine pack_data_I2_R4
All Procedures
b64_decode b64_decode_I1 b64_decode_I1_a b64_decode_I2 b64_decode_I2_a b64_decode_I4 b64_decode_I4_a b64_decode_I8 b64_decode_I8_a b64_decode_R16 b64_decode_R16_a b64_decode_R4 b64_decode_R4_a b64_decode_R8 b64_decode_R8_a b64_decode_string b64_decode_string_a b64_decode_up b64_decode_up b64_decode_up_a b64_encode b64_encode_I1 b64_encode_I1_a b64_encode_I2 b64_encode_I2_a b64_encode_I4 b64_encode_I4_a b64_encode_I8 b64_encode_I8_a b64_encode_R16 b64_encode_R16_a b64_encode_R4 b64_encode_R4_a b64_encode_R8 b64_encode_R8_a b64_encode_string b64_encode_string_a b64_encode_up b64_encode_up b64_encode_up_a b64_init decode_bits encode_bits pack_data pack_data_I1_I2 pack_data_I1_I4 pack_data_I1_I8 pack_data_I1_R4 pack_data_I1_R8 pack_data_I2_I1 pack_data_I2_I4 pack_data_I2_I8 pack_data_I2_R4 pack_data_I2_R8 pack_data_I4_I1 pack_data_I4_I2 pack_data_I4_I8 pack_data_I4_R4 pack_data_I4_R8 pack_data_I8_I1 pack_data_I8_I2 pack_data_I8_I4 pack_data_I8_R4 pack_data_I8_R8 pack_data_R4_I1 pack_data_R4_I2 pack_data_R4_I4 pack_data_R4_I8 pack_data_R4_R8 pack_data_R8_I1 pack_data_R8_I2 pack_data_R8_I4 pack_data_R8_I8 pack_data_R8_R4
Call graph
pack_data calls pack_data_i2_r4
volatile_doctest calls pack_data