b64_encode – BeFoR64
b64_encode Interface
3 statements
Source File
public interface b64_encode
Encode numbers (integer and real) to base64.
This is an interface for encoding integer and real numbers of any kinds into a base64 string. This interface can encode both scalar and array.
Warning
The encoded string is returned as varying length character string, character(len=:), allocatable:: string, thus the compiler must support such a Fortran (2003) feature.
Note
Before start to encode anything the library must be initialized. The procedure b64_init must be called at first. The global variable is_b64_initialized can be used to check the status of the initialization.
Usage
For a practical example see the autotest procedure.
Scalar encoding
character(len=:), allocatable:: code64 ! base64 encoded string
...
call b64_encode(n=12._R8P,code=code64)
Array encoding
character(len=:), allocatable:: code64 ! base64 encoded string
...
call b64_encode(n=[12_I4P,1_I4P],code=code64)
Note
If you want to encode heterogenous data (e.g. integer and real numbers), you must use the auxiliary pack_data procedure.
Warning
The encoding of array of strings is admitted only if each string of the array has the same length.
Calls
Called By
Module Procedures
b64_encode_R8 b64_encode_R8_a b64_encode_R4 b64_encode_R4_a b64_encode_I8 b64_encode_I8_a b64_encode_I4 b64_encode_I4_a b64_encode_I2 b64_encode_I2_a b64_encode_I1 b64_encode_I1_a b64_encode_string b64_encode_string_a
Module Procedures
private pure subroutine b64_encode_R8(n, code)
Encode scalar number to base64 (R8P).
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
Number to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
private pure subroutine b64_encode_R8_a(n, code)
Encode array numbers to base64 (R8P).
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(1:)
Array of numbers to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
private pure subroutine b64_encode_R4(n, code)
Encode scalar number to base64 (R4P).
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n
Number to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
private pure subroutine b64_encode_R4_a(n, code)
Encode array numbers to base64 (R4P).
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(1:)
Array of numbers to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
private pure subroutine b64_encode_I8(n, code)
Encode scalar number to base64 (I8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
Number to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
private pure subroutine b64_encode_I8_a(n, code)
Encode array numbers to base64 (I8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n(1:)
Array of numbers to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
private pure subroutine b64_encode_I4(n, code)
Encode scalar number to base64 (I4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
Number to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
private pure subroutine b64_encode_I4_a(n, code)
Encode array numbers to base64 (I4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n(1:)
Array of numbers to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
private pure subroutine b64_encode_I2(n, code)
Encode scalar number to base64 (I2P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
Number to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
private pure subroutine b64_encode_I2_a(n, code)
Encode array numbers to base64 (I2P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n(1:)
Array of numbers to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
private pure subroutine b64_encode_I1(n, code)
Encode scalar number to base64 (I1P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
Number to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
private pure subroutine b64_encode_I1_a(n, code)
Encode array numbers to base64 (I1P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n(1:)
Array of numbers to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
private pure subroutine b64_encode_string(s, code)
Encode scalar string to base64.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
String to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
private pure subroutine b64_encode_string_a(s, code)
Encode array string to base64.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s(1:)
String to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
All Procedures
b64_decode b64_decode_I1 b64_decode_I1_a b64_decode_I2 b64_decode_I2_a b64_decode_I4 b64_decode_I4_a b64_decode_I8 b64_decode_I8_a b64_decode_R16 b64_decode_R16_a b64_decode_R4 b64_decode_R4_a b64_decode_R8 b64_decode_R8_a b64_decode_string b64_decode_string_a b64_decode_up b64_decode_up b64_decode_up_a b64_encode b64_encode_I1 b64_encode_I1_a b64_encode_I2 b64_encode_I2_a b64_encode_I4 b64_encode_I4_a b64_encode_I8 b64_encode_I8_a b64_encode_R16 b64_encode_R16_a b64_encode_R4 b64_encode_R4_a b64_encode_R8 b64_encode_R8_a b64_encode_string b64_encode_string_a b64_encode_up b64_encode_up b64_encode_up_a b64_init decode_bits encode_bits pack_data pack_data_I1_I2 pack_data_I1_I4 pack_data_I1_I8 pack_data_I1_R4 pack_data_I1_R8 pack_data_I2_I1 pack_data_I2_I4 pack_data_I2_I8 pack_data_I2_R4 pack_data_I2_R8 pack_data_I4_I1 pack_data_I4_I2 pack_data_I4_I8 pack_data_I4_R4 pack_data_I4_R8 pack_data_I8_I1 pack_data_I8_I2 pack_data_I8_I4 pack_data_I8_R4 pack_data_I8_R8 pack_data_R4_I1 pack_data_R4_I2 pack_data_R4_I4 pack_data_R4_I8 pack_data_R4_R8 pack_data_R8_I1 pack_data_R8_I2 pack_data_R8_I4 pack_data_R8_I8 pack_data_R8_R4
Call graph
b64_encode calls b64_encode_r4_a, b64_encode_r4, b64_encode_i8_a, b64_encode_i1, b64_encode_r8, b64_encode_string_a, b64_encode_i2, b64_encode_string, b64_encode_i1_a, b64_encode_i8, b64_encode_i4_a, b64_encode_r8_a, b64_encode_i2_a, b64_encode_i4
b64_encode_r4_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_i1 calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_string_a calls encode_bits, byte_size
b64_encode_i2 calls encode_bits
b64_encode_string calls encode_bits, byte_size
b64_encode_i1_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
volatile_doctest calls b64_encode