b64_decode – BeFoR64
b64_decode Interface
3 statements
Source File
public interface b64_decode
Decode numbers (integer and real) from base64.
This is an interface for decoding integer and real numbers of any kinds from a base64 string. This interface can decode both scalar and array.
Note
Before start to decode anything the library must be initialized. The procedure b64_init must be called at first. The global variable is_b64_initialized can be used to check the status of the initialization.
Usage
For a practical example see the autotest procedure.
Scalar decoding
real(R8P):: decoded ! scalar to be decoded
...
call b64_decode(code='AAAAAAAA8D8=',n=decoded)
Array decoding
integer(I8P):: decoded(1:4) ! array to be decoded
...
call b64_decode(code='FwAAAAAAAABEAQAAAAAAABBwhAEAAAAAAgAAAAAAAAA=',n=decoded)
Note
If you want to decode heterogenous data (e.g. integer and real numbers), you must use the auxiliary pack_data procedure.
Warning
The decoding of array of strings is admitted only if each string of the array has the same length.
Calls
Called By
Module Procedures
b64_decode_R8 b64_decode_R8_a b64_decode_R4 b64_decode_R4_a b64_decode_I8 b64_decode_I8_a b64_decode_I4 b64_decode_I4_a b64_decode_I2 b64_decode_I2_a b64_decode_I1 b64_decode_I1_a b64_decode_string b64_decode_string_a
Module Procedures
private elemental subroutine b64_decode_R8(code, n)
Decode a base64 code into a scalar number (R8P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
real(kind=R8P), intent(out) :: n
Number to be decoded.
private pure subroutine b64_decode_R8_a(code, n)
Decode a base64 code into an array numbers (R8P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded array.
real(kind=R8P), intent(out) :: n(1:)
Array of numbers to be decoded.
private elemental subroutine b64_decode_R4(code, n)
Decode a base64 code into a scalar number (R4P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
real(kind=R4P), intent(out) :: n
Number to be decoded.
private pure subroutine b64_decode_R4_a(code, n)
Decode a base64 code into an array numbers (R4P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded array.
real(kind=R4P), intent(out) :: n(1:)
Array of numbers to be decoded.
private elemental subroutine b64_decode_I8(code, n)
Decode a base64 code into a scalar number (I8P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
integer(kind=I8P), intent(out) :: n
Number to be decoded.
private pure subroutine b64_decode_I8_a(code, n)
Decode a base64 code into an array numbers (I8P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded array.
integer(kind=I8P), intent(out) :: n(1:)
Array of numbers to be decoded.
private elemental subroutine b64_decode_I4(code, n)
Decode a base64 code into a scalar number (I4P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
integer(kind=I4P), intent(out) :: n
Number to be decoded.
private pure subroutine b64_decode_I4_a(code, n)
Decode a base64 code into an array numbers (I4P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded array.
integer(kind=I4P), intent(out) :: n(1:)
Array of numbers to be decoded.
private elemental subroutine b64_decode_I2(code, n)
Decode a base64 code into a scalar number (I2P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
integer(kind=I2P), intent(out) :: n
Number to be decoded.
private pure subroutine b64_decode_I2_a(code, n)
Decode a base64 code into an array numbers (I2P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded array.
integer(kind=I2P), intent(out) :: n(1:)
Array of numbers to be decoded.
private elemental subroutine b64_decode_I1(code, n)
Decode a base64 code into a scalar number (I1P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
integer(kind=I1P), intent(out) :: n
Number to be decoded.
private pure subroutine b64_decode_I1_a(code, n)
Decode a base64 code into an array numbers (I1P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded array.
integer(kind=I1P), intent(out) :: n(1:)
Array of numbers to be decoded.
private elemental subroutine b64_decode_string(code, s)
Decode a base64 code into a scalar string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
character(len=*), intent(out) :: s
String to be decoded.
private pure subroutine b64_decode_string_a(code, s)
Decode a base64 code into an array of strings.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
character(len=*), intent(out) :: s(1:)
String to be decoded.
All Procedures
b64_decode b64_decode_I1 b64_decode_I1_a b64_decode_I2 b64_decode_I2_a b64_decode_I4 b64_decode_I4_a b64_decode_I8 b64_decode_I8_a b64_decode_R16 b64_decode_R16_a b64_decode_R4 b64_decode_R4_a b64_decode_R8 b64_decode_R8_a b64_decode_string b64_decode_string_a b64_decode_up b64_decode_up b64_decode_up_a b64_encode b64_encode_I1 b64_encode_I1_a b64_encode_I2 b64_encode_I2_a b64_encode_I4 b64_encode_I4_a b64_encode_I8 b64_encode_I8_a b64_encode_R16 b64_encode_R16_a b64_encode_R4 b64_encode_R4_a b64_encode_R8 b64_encode_R8_a b64_encode_string b64_encode_string_a b64_encode_up b64_encode_up b64_encode_up_a b64_init decode_bits encode_bits pack_data pack_data_I1_I2 pack_data_I1_I4 pack_data_I1_I8 pack_data_I1_R4 pack_data_I1_R8 pack_data_I2_I1 pack_data_I2_I4 pack_data_I2_I8 pack_data_I2_R4 pack_data_I2_R8 pack_data_I4_I1 pack_data_I4_I2 pack_data_I4_I8 pack_data_I4_R4 pack_data_I4_R8 pack_data_I8_I1 pack_data_I8_I2 pack_data_I8_I4 pack_data_I8_R4 pack_data_I8_R8 pack_data_R4_I1 pack_data_R4_I2 pack_data_R4_I4 pack_data_R4_I8 pack_data_R4_R8 pack_data_R8_I1 pack_data_R8_I2 pack_data_R8_I4 pack_data_R8_I8 pack_data_R8_R4
Call graph
b64_decode calls b64_decode_r4_a, b64_decode_i2_a, b64_decode_i1, b64_decode_r8, b64_decode_string, b64_decode_i8, b64_decode_i2, b64_decode_i8_a, b64_decode_r8_a, b64_decode_i4, b64_decode_r4, b64_decode_string_a, b64_decode_i4_a, b64_decode_i1_a
b64_decode_r4_a calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_i1 calls decode_bits
b64_decode_r8 calls decode_bits
b64_decode_string calls decode_bits, byte_size
b64_decode_i8 calls decode_bits
b64_decode_i2 calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i4 calls decode_bits
b64_decode_r4 calls decode_bits
b64_decode_string_a calls decode_bits, byte_size
b64_decode_i4_a calls decode_bits
b64_decode_i1_a calls decode_bits
volatile_doctest calls b64_decode