pack_data – BeFoR64
pack_data Interface
3 statements
Source File
public interface pack_data
Pack different kinds of data into single I1P array.
This is useful for encoding different (heterogeneous) kinds variables into a single (homogeneous) stream of bits.
Note
This procedure exploits the transfer builtin function, that from the standard (2003+) is defined as TRANSFER(SOURCE, MOLD [, SIZE]). Data object having a physical representation identical to that of SOURCE but with the type and type parameters of MOLD. The result is of the same type and type parameters as MOLD. If MOLD is an array and SIZE is absent, the result is an array and of rank one. Its size is as small as possible such that its physical representation is not shorter than that of SOURCE.
Presently, the following combinations are available:
Arrays-Arrays:
real(any)-real(any);
real(any)-integer(any);
integer(any)-integer(any);
integer(any)-real(any);
real(any)-character;
character-real(any);
integer(any)-character;
character-integer(any);
Scalars-Scalars:
real(any)-real(any);
real(any)-integer(any);
integer(any)-integer(any);
integer(any)-real(any);
real(any)-character;
character-real(any);
integer(any)-character;
character-integer(any);
Examples of usage
Packing two real arrays, one with kind R8P and one with R4P
real(R8P)::                 array_r8(1:12)
real(R4P)::                 array_r4(-1:5)
integer(I1P), allocatable:: rpack
...
call pack_data(a1=array_r8,a2=array_r4,packed=rpack)
Packing two arrays, one real with kind R4P and one integer with I4P
real(R4P)::                 array_r4(2)
integer(I4P)::              array_i4(0:2)
integer(I1P), allocatable:: rpack
...
call pack_data(a1=array_r4,a2=array_i4,packed=rpack)
Calls
Called By
Module Procedures
pack_data_R8_R4 pack_data_R8_I8 pack_data_R8_I4 pack_data_R8_I2 pack_data_R8_I1 pack_data_R4_R8 pack_data_R4_I8 pack_data_R4_I4 pack_data_R4_I2 pack_data_R4_I1 pack_data_I8_R8 pack_data_I8_R4 pack_data_I8_I4 pack_data_I8_I2 pack_data_I8_I1 pack_data_I4_R8 pack_data_I4_R4 pack_data_I4_I8 pack_data_I4_I2 pack_data_I4_I1 pack_data_I2_R8 pack_data_I2_R4 pack_data_I2_I8 pack_data_I2_I4 pack_data_I2_I1 pack_data_I1_R8 pack_data_I1_R4 pack_data_I1_I8 pack_data_I1_I4 pack_data_I1_I2
Module Procedures
private pure subroutine pack_data_R8_R4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
Firs data stream.
real(kind=R4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R8_I8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
First data stream.
integer(kind=I8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R8_I4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
First data stream.
integer(kind=I4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R8_I2(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
First data stream.
integer(kind=I2P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R8_I1(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: a1(1:)
First data stream.
integer(kind=I1P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R4_R8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
Firs data stream.
real(kind=R8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R4_I8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
First data stream.
integer(kind=I8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R4_I4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
First data stream.
integer(kind=I4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R4_I2(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
First data stream.
integer(kind=I2P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_R4_I1(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: a1(1:)
First data stream.
integer(kind=I1P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I8_R8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
First data stream.
real(kind=R8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I8_R4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
First data stream.
real(kind=R4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I8_I4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
First data stream.
integer(kind=I4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I8_I2(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
First data stream.
integer(kind=I2P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I8_I1(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: a1(1:)
First data stream.
integer(kind=I1P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I4_R8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
First data stream.
real(kind=R8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I4_R4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
First data stream.
real(kind=R4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I4_I8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
First data stream.
integer(kind=I8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I4_I2(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
First data stream.
integer(kind=I2P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I4_I1(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: a1(1:)
First data stream.
integer(kind=I1P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I2_R8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
First data stream.
real(kind=R8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I2_R4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
First data stream.
real(kind=R4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I2_I8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
First data stream.
integer(kind=I8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I2_I4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
First data stream.
integer(kind=I4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I2_I1(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: a1(1:)
First data stream.
integer(kind=I1P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I1_R8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
First data stream.
real(kind=R8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I1_R4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
First data stream.
real(kind=R4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I1_I8(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
First data stream.
integer(kind=I8P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I1_I4(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
First data stream.
integer(kind=I4P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
private pure subroutine pack_data_I1_I2(a1, a2, packed)
Pack different kinds of data into single I1P array.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: a1(1:)
First data stream.
integer(kind=I2P), intent(in) :: a2(1:)
Second data stream.
integer(kind=I1P), intent(inout), allocatable :: packed(:)
Packed data into I1P array.
All Procedures
b64_decode b64_decode_I1 b64_decode_I1_a b64_decode_I2 b64_decode_I2_a b64_decode_I4 b64_decode_I4_a b64_decode_I8 b64_decode_I8_a b64_decode_R16 b64_decode_R16_a b64_decode_R4 b64_decode_R4_a b64_decode_R8 b64_decode_R8_a b64_decode_string b64_decode_string_a b64_decode_up b64_decode_up b64_decode_up_a b64_encode b64_encode_I1 b64_encode_I1_a b64_encode_I2 b64_encode_I2_a b64_encode_I4 b64_encode_I4_a b64_encode_I8 b64_encode_I8_a b64_encode_R16 b64_encode_R16_a b64_encode_R4 b64_encode_R4_a b64_encode_R8 b64_encode_R8_a b64_encode_string b64_encode_string_a b64_encode_up b64_encode_up b64_encode_up_a b64_init decode_bits encode_bits pack_data pack_data_I1_I2 pack_data_I1_I4 pack_data_I1_I8 pack_data_I1_R4 pack_data_I1_R8 pack_data_I2_I1 pack_data_I2_I4 pack_data_I2_I8 pack_data_I2_R4 pack_data_I2_R8 pack_data_I4_I1 pack_data_I4_I2 pack_data_I4_I8 pack_data_I4_R4 pack_data_I4_R8 pack_data_I8_I1 pack_data_I8_I2 pack_data_I8_I4 pack_data_I8_R4 pack_data_I8_R8 pack_data_R4_I1 pack_data_R4_I2 pack_data_R4_I4 pack_data_R4_I8 pack_data_R4_R8 pack_data_R8_I1 pack_data_R8_I2 pack_data_R8_I4 pack_data_R8_I8 pack_data_R8_R4
Call graph
pack_data calls pack_data_r4_i2, pack_data_r4_i4, pack_data_i4_i1, pack_data_i2_i1, pack_data_r4_i8, pack_data_i2_r4, pack_data_i4_r4, pack_data_i2_r8, pack_data_r8_i2, pack_data_r4_r8, pack_data_i4_i2, pack_data_i1_r4, pack_data_r8_i8, pack_data_r8_i4, pack_data_i1_r8, pack_data_r8_r4, pack_data_i4_r8, pack_data_i2_i4, pack_data_i1_i2, pack_data_i1_i8, pack_data_i8_i1, pack_data_i8_i2, pack_data_r8_i1, pack_data_i8_i4, pack_data_i8_r4, pack_data_i4_i8, pack_data_i1_i4, pack_data_i8_r8, pack_data_r4_i1, pack_data_i2_i8
volatile_doctest calls pack_data