befor64_test – BeFoR64
befor64_test Program
5 statements
Source File
Uses:
befor64
Testing program for BeFoR64, Base64 encoding/decoding library for FoRtran poor men
Usage
 ./Test_Driver
Calls
Source Code
befor64_test
Source Code
program befor64_test
!< Testing program for BeFoR64, Base64 encoding/decoding library for FoRtran poor men
!<
!<### Usage
!<```bash
!< ./Test_Driver
!<```
use befor64, only : autotest ! Autotesting procedure.
implicit none
call autotest
endprogram befor64_test
All Programs
befor64_test
Call graph
befor64_test calls autotest
autotest calls b64_encode, b64_decode, b64_init, str
b64_encode calls b64_encode_i1, b64_encode_i4, b64_encode_string, b64_encode_i2_a, b64_encode_i8, b64_encode_r8_a, b64_encode_i4_a, b64_encode_r8, b64_encode_i1_a, b64_encode_r4_a, b64_encode_r4, b64_encode_string_a, b64_encode_i8_a, b64_encode_i2
b64_decode calls b64_decode_r8, b64_decode_i1_a, b64_decode_i2, b64_decode_r4, b64_decode_r4_a, b64_decode_string, b64_decode_i8, b64_decode_i1, b64_decode_i8_a, b64_decode_string_a, b64_decode_i4, b64_decode_i2_a, b64_decode_r8_a, b64_decode_i4_a
b64_encode_i1 calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_string calls encode_bits, byte_size
b64_encode_i2_a calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_string_a calls encode_bits, byte_size
b64_encode_i8_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_decode_r8 calls decode_bits
b64_decode_i1_a calls decode_bits
b64_decode_i2 calls decode_bits
b64_decode_r4 calls decode_bits
b64_decode_r4_a calls decode_bits
b64_decode_string calls byte_size, decode_bits
b64_decode_i8 calls decode_bits
b64_decode_i1 calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_string_a calls byte_size, decode_bits
b64_decode_i4 calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i4_a calls decode_bits