volatile_doctest – BeFoR64
volatile_doctest Program
12 statements
Source File
Uses:
befor64_pack_data_m
befor64
penf
Calls
Variables
a1 a2 pack
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
real(kind=R8P) :: a1(1)
integer(kind=I8P) :: a2(1)
integer(kind=I1P), allocatable :: pack(:)
Source Code
program volatile_doctest
use befor64_pack_data_m
 use befor64
 use penf
 real(R8P)                 :: a1(1)
 integer(I8P)              :: a2(1)
 integer(I1P), allocatable :: pack(:)
 a1(1) = 0
 a2(1) = 1
 call pack_data(a1=a1, a2=a2, packed=pack)
 print *, pack(9)
endprogram volatile_doctest
All Programs
volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest
Call graph
volatile_doctest calls pack_data
pack_data calls pack_data_r4_i2, pack_data_r4_i4, pack_data_i4_i1, pack_data_i2_i1, pack_data_r4_i8, pack_data_i2_r4, pack_data_i4_r4, pack_data_i2_r8, pack_data_r8_i2, pack_data_r4_r8, pack_data_i4_i2, pack_data_i1_r4, pack_data_r8_i8, pack_data_r8_i4, pack_data_i1_r8, pack_data_r8_r4, pack_data_i4_r8, pack_data_i2_i4, pack_data_i1_i2, pack_data_i1_i8, pack_data_i8_i1, pack_data_i8_i2, pack_data_r8_i1, pack_data_i8_i4, pack_data_i8_r4, pack_data_i4_i8, pack_data_i1_i4, pack_data_i8_r8, pack_data_r4_i1, pack_data_i2_i8