volatile_doctest – BeFoR64
volatile_doctest Program
8 statements
Source File
Uses:
befor64
befor64
penf
Calls
Variables
array_R8
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
real(kind=R8P) :: array_R8(1:2)
Source Code
program volatile_doctest
use befor64
 use befor64
 use penf
 real(R8P) :: array_R8(1:2)
 call b64_decode(code='AAAAAAAA8D8AAAAAAAAAQA==',n=array_R8)
 print "(L1)", str(n=array_R8)==str(n=[1._R8P,2._R8P])
endprogram volatile_doctest
All Programs
volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest
Call graph
volatile_doctest calls b64_decode, str
b64_decode calls b64_decode_r4_a, b64_decode_i2_a, b64_decode_i1, b64_decode_r8, b64_decode_string, b64_decode_i8, b64_decode_i2, b64_decode_i8_a, b64_decode_r8_a, b64_decode_i4, b64_decode_r4, b64_decode_string_a, b64_decode_i4_a, b64_decode_i1_a
b64_decode_r4_a calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_i1 calls decode_bits
b64_decode_r8 calls decode_bits
b64_decode_string calls decode_bits, byte_size
b64_decode_i8 calls decode_bits
b64_decode_i2 calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i4 calls decode_bits
b64_decode_r4 calls decode_bits
b64_decode_string_a calls decode_bits, byte_size
b64_decode_i4_a calls decode_bits
b64_decode_i1_a calls decode_bits